workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        BUNDLE_ID: "com.Tactil-Calm"
        XCODE_PROJECT: "TactilCalm.xcodeproj" # Xcode project (не workspace)
        XCODE_SCHEME: "TactilCalm"            # Имя shared scheme
        APP_STORE_APPLE_ID: 6755437518
      xcode: 16.2
      flutter: none # если это не Flutter-проект
    scripts:
      - name: Clean build folder
        script: |
          xcodebuild clean -project $XCODE_PROJECT -scheme $XCODE_SCHEME -configuration Release
      - name: Build IPA
        script: |
          xcodebuild archive \
            -project $XCODE_PROJECT \
            -scheme $XCODE_SCHEME \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/$XCODE_SCHEME.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/$XCODE_SCHEME.xcarchive \
            -exportPath $CM_BUILD_DIR/build/ipa \
            -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/ipa/*.ipa

